### PR TITLE
 Spack-side of moving Tribol to Serac

### PR DESCRIPTION
**Pull request by chapman39**
Currently just the spack stuff has been setup. 

Still need todo cmake and src work to move tribol, and maybe more? This is planned for a future PR.

The tribol spack package has been updated as well. I took the spack package from the tribol project itself, copied it here, and moved to a newer tribol version https://github.com/LLNL/Tribol/commit/c62690d8c21f94110d1f97d50c89fa87d142bb59.

### CODE REVIEW

File: scripts/spack/packages/tribol/package.py [hunk 1]
```diff
@@ -0,0 +1,300 @@
...
+
+    return path
+
+# NOTE: Cannot inherit from builtin until tribol becomes a builtin spack package within spack itself.
+
+class Tribol(CachedCMakePackage, CudaPackage):
+    """Tribol is an interface physics library."""
+
+    homepage = "https://lc.llnl.gov/gitlab/tribol/tribol"
+    git      = "ssh://git@czgitlab.llnl.gov:7999/tribol/tribol.git"
```
Comment (white238) [inline scripts/spack/packages/tribol/package.py]: These arent correct, though when you change to the github repo you will lose the commit below. They didn't keep their git history when they moved.

Comment (chapman39) [reply scripts/spack/packages/tribol/package.py]: should it be:
```
    homepage = "https://lc.llnl.gov/gitlab/tribol/tribol"
    git      = "https://lc.llnl.gov/gitlab/tribol/tribol.git"
```
?

or should we point to their github

Comment (chapman39) [reply scripts/spack/packages/tribol/package.py]: update: the links should be correct now. i moved the commit to one on their github. i also removed the patch since the changes are in the proj itself.

https://github.com/LLNL/Tribol/commit/c62690d8c21f94110d1f97d50c89fa87d142bb59

**Comment by jamiebramwell** [comment]
@white238 , should we do a TPL rebuild here?

**Comment by white238** [comment]
Yes this should be a rebuild.

File: scripts/spack/packages/tribol/package.py [hunk 2]
```diff
@@ -0,0 +1,299 @@
...
+    homepage = "https://github.com/LLNL/Tribol"
+    git      = "https://github.com/LLNL/Tribol.git"
+
+    version("develop", branch="develop", submodules=True)
+
+
+    # SERAC EDIT START
+    # Note: We add a number to the end of the real version number to indicate that we have
+    #  moved forward past the release. Increment the last number when updating the commit sha.
+    version('0.1.0.5', commit='c62690d8c21f94110d1f97d50c89fa87d142bb59', submodules=True, preferred=True)
```
Comment (ebchin) [inline scripts/spack/packages/tribol/package.py]: Would it be possible to point to this commit for now: [`3ed15810a8cf9cebda84f97ee35fa5ee88154fc5`](https://github.com/LLNL/Tribol/pull/11/commits/3ed15810a8cf9cebda84f97ee35fa5ee88154fc5).  It's still part of a Tribol PR, but it has the interface that I'll be hooking up to serac.

File: scripts/spack/specs.json [hunk 3]
```diff
@@ -22,7 +22,7 @@
       "clang@14.0.6+devtools+profiling" ],
 
     "blueos_3_ppc64le_ib_p9":
-    [ "clang@10.0.1+devtools+cuda+raja+umpire+profiling cuda_arch=70" ],
+    [ "clang@10.0.1~tribol+devtools+cuda+raja+umpire+profiling cuda_arch=70" ],
```
Comment (ebchin) [inline scripts/spack/specs.json:25]: I haven't looked at the blueos tribol cuda build in a while.  Is it not working when building with serac?  You might need to append `+cuda+raja+umpire` to the tribol spec.

Comment (white238) [reply scripts/spack/specs.json:25]: It wasn't working a very long time ago and we never went back and tried it. We should probably revisit that.

Comment (chapman39) [reply scripts/spack/specs.json:25]: would it hurt to always add `+raja+umpire` and only add `+cuda` to tribol if it's part of serac's spec?

```
    depends_on("tribol+raja+umpire", when="+tribol")
    depends_on("tribol+cuda", when="+tribol+cuda")
```

Comment (chapman39) [reply scripts/spack/specs.json:25]: if we do `tribol+raja+umpire` we may also need `~minbuild`, to prevent raja to build without openmp

Comment (ebchin) [reply scripts/spack/specs.json:25]: `+raja+umpire` should be fine; we currently test Tribol with serac's TPLs which have raja and umpire built.

**Comment by chapman39** [comment]
I've been getting a bunch of errors when building `functional_shape_derivatives` on rzgenie gcc@8.3.1. Does anyone use rzgenie despite it being Toss3? Should we try and build on something like rztopaz instead?

A small portion of the error. It seems to be complaining about an unused parameter, but I do see `X` being used in `grad_monomials`.
```
[ 37%] Building CXX object src/serac/numerics/functional/tests/CMakeFiles/functional_shape_derivatives.dir/functional_shape_derivatives.cpp.o
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp: In instantiation of 'auto grad_monomials(serac::tensor<T, m>) [with int p = 1; T = double; int dim = 2]':
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:240:64:   required from 'functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:25)> [with auto:25 = serac::tensor<double, 2>]'
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:245:34:   required from 'functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)> [with auto:26 = serac::tensor<double, 2>; auto:27 = serac::tuple<serac::tensor<double, 2>, serac::tensor<double, 2, 2> >]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:104:34:   required from 'auto serac::domain_integral::batch_apply_qf_no_qdata(lambda, serac::tensor<double, c, dim>, const T& ...) [with lambda = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; int dim = 2; int n = 3; T = {serac::tensor<serac::tuple<serac::tensor<double, 2>, serac::tensor<double, 2, 2> >, 3>}]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:182:39:   required from 'void serac::domain_integral::evaluation_kernel_impl(FunctionSignature<test(trials ...)>, const std::vector<const double*>&, double*, const double*, const double*, lambda_type, axom::ArrayView<state_type, 2>, derivative_type*, uint32_t, bool, std::integer_sequence<int, indices ...>) [with unsigned int differentiation_index = 2147483648; int Q = 2; mfem::Geometry::Type geom = (mfem::Geometry::Type)2; test = serac::H1<1, 1>; trials = {serac::H1<1, 2>}; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; state_type = serac::Nothing; derivative_type = serac::zero; int ...indices = {0}; uint32_t = unsigned int]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:354:58:   required from 'std::function<void(const std::vector<const double*>&, double*, bool)> serac::domain_integral::evaluation_kernel(signature, lambda_type, const double*, const double*, std::shared_ptr<serac::QuadratureData<state_type> >, std::shared_ptr<derivative_type>, uint32_t) [with unsigned int wrt = 2147483648; int Q = 2; mfem::Geometry::Type geom = (mfem::Geometry::Type)2; signature = FunctionSignature<serac::H1<1, 1>(serac::H1<1, 2>)>; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; state_type = serac::Nothing; derivative_type = serac::zero; uint32_t = unsigned int]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/integral.hpp:214:95:   required from 'void serac::generate_kernels(FunctionSignature<test(trials ...)>, serac::Integral&, lambda_type&&, mfem::Mesh&, std::shared_ptr<serac::QuadratureData<state_type> >) [with mfem::Geometry::Type geom = (mfem::Geometry::Type)2; int Q = 2; test = serac::H1<1, 1>; trials = {serac::H1<1, 2>}; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>&; qpt_data_type = serac::Nothing]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/integral.hpp:260:50:   required from 'serac::Integral serac::MakeDomainIntegral(mfem::Mesh&, lambda_type&&, std::shared_ptr<serac::QuadratureData<qpt_data_type> >, std::vector<unsigned int>) [with s = serac::H1<1, 1>(serac::H1<1, 2>); int Q = 2; int dim = 2; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>&; qpt_data_type = serac::Nothing]'
/usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/functional.hpp:294:46:   required from 'void serac::Functional<test(trials ...), exec>::AddDomainIntegral(serac::Dimension<dim>, serac::DependsOn<args ...>, lambda&&, mfem::Mesh&, std::shared_ptr<serac::QuadratureData<qpt_data_type> >) [with int dim = 2; int ...args = {1}; lambda = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; qpt_data_type = serac::Nothing; test = serac::H1<1, 1>; trials = {serac::H1<1, 1>, serac::H1<1, 2>}; serac::ExecutionSpace exec = (serac::ExecutionSpace)0]'
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:241:3:   required from 'void functional_test_2D(mfem::ParMesh&, double) [with int p = 1]'
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:333:73:   required from here
/usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:126:36: error: parameter 'X' set but not used [-Werror=unused-but-set-parameter]
 auto grad_monomials(tensor<T, dim> X)
                     ~~~~~~~~~~~~~~~^
```

File: scripts/spack/specs.json (hunk 3 above)
Comment (chapman39) [reply scripts/spack/specs.json:25]: i decided to not include those variants for now. we can try and look into adding them once we attempt to build on lassen again in a separate pr.

**Comment by chapman39** [comment]
I should also mention it builds fine on rzgenie clang@10.0.0. its just gcc that fails ^

**Comment by jamiebramwell** [comment]
I've been getting a bunch of errors when building functional_shape_derivatives on rzgenie gcc@8.3.1. Does anyone use rzgenie despite it being Toss3? Should we try and build on something like rzwhippet instead?

    A small portion of the error. It seems to be complaining about an unused parameter, but I do see X being used in grad_monomials.

    [ 37%] Building CXX object src/serac/numerics/functional/tests/CMakeFiles/functional_shape_derivatives.dir/functional_shape_derivatives.cpp.o
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp: In instantiation of 'auto grad_monomials(serac::tensor<T, m>) [with int p = 1; T = double; int dim = 2]':
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:240:64:   required from 'functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:25)> [with auto:25 = serac::tensor<double, 2>]'
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:245:34:   required from 'functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)> [with auto:26 = serac::tensor<double, 2>; auto:27 = serac::tuple<serac::tensor<double, 2>, serac::tensor<double, 2, 2> >]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:104:34:   required from 'auto serac::domain_integral::batch_apply_qf_no_qdata(lambda, serac::tensor<double, c, dim>, const T& ...) [with lambda = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; int dim = 2; int n = 3; T = {serac::tensor<serac::tuple<serac::tensor<double, 2>, serac::tensor<double, 2, 2> >, 3>}]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:182:39:   required from 'void serac::domain_integral::evaluation_kernel_impl(FunctionSignature<test(trials ...)>, const std::vector<const double*>&, double*, const double*, const double*, lambda_type, axom::ArrayView<state_type, 2>, derivative_type*, uint32_t, bool, std::integer_sequence<int, indices ...>) [with unsigned int differentiation_index = 2147483648; int Q = 2; mfem::Geometry::Type geom = (mfem::Geometry::Type)2; test = serac::H1<1, 1>; trials = {serac::H1<1, 2>}; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; state_type = serac::Nothing; derivative_type = serac::zero; int ...indices = {0}; uint32_t = unsigned int]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/domain_integral_kernels.hpp:354:58:   required from 'std::function<void(const std::vector<const double*>&, double*, bool)> serac::domain_integral::evaluation_kernel(signature, lambda_type, const double*, const double*, std::shared_ptr<serac::QuadratureData<state_type> >, std::shared_ptr<derivative_type>, uint32_t) [with unsigned int wrt = 2147483648; int Q = 2; mfem::Geometry::Type geom = (mfem::Geometry::Type)2; signature = FunctionSignature<serac::H1<1, 1>(serac::H1<1, 2>)>; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; state_type = serac::Nothing; derivative_type = serac::zero; uint32_t = unsigned int]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/integral.hpp:214:95:   required from 'void serac::generate_kernels(FunctionSignature<test(trials ...)>, serac::Integral&, lambda_type&&, mfem::Mesh&, std::shared_ptr<serac::QuadratureData<state_type> >) [with mfem::Geometry::Type geom = (mfem::Geometry::Type)2; int Q = 2; test = serac::H1<1, 1>; trials = {serac::H1<1, 2>}; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>&; qpt_data_type = serac::Nothing]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/integral.hpp:260:50:   required from 'serac::Integral serac::MakeDomainIntegral(mfem::Mesh&, lambda_type&&, std::shared_ptr<serac::QuadratureData<qpt_data_type> >, std::vector<unsigned int>) [with s = serac::H1<1, 1>(serac::H1<1, 2>); int Q = 2; int dim = 2; lambda_type = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>&; qpt_data_type = serac::Nothing]'
    /usr/WS1/asmith/serac_repo/src/serac/infrastructure/../../serac/numerics/functional/functional.hpp:294:46:   required from 'void serac::Functional<test(trials ...), exec>::AddDomainIntegral(serac::Dimension<dim>, serac::DependsOn<args ...>, lambda&&, mfem::Mesh&, std::shared_ptr<serac::QuadratureData<qpt_data_type> >) [with int dim = 2; int ...args = {1}; lambda = functional_test_2D(mfem::ParMesh&, double) [with int p = 1]::<lambda(auto:26, auto:27)>; qpt_data_type = serac::Nothing; test = serac::H1<1, 1>; trials = {serac::H1<1, 1>, serac::H1<1, 2>}; serac::ExecutionSpace exec = (serac::ExecutionSpace)0]'
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:241:3:   required from 'void functional_test_2D(mfem::ParMesh&, double) [with int p = 1]'
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:333:73:   required from here
    /usr/WS1/asmith/serac_repo/src/serac/numerics/functional/tests/functional_shape_derivatives.cpp:126:36: error: parameter 'X' set but not used [-Werror=unused-but-set-parameter]
     auto grad_monomials(tensor<T, dim> X)
                         ~~~~~~~~~~~~~~~^

I think genie is going away soon. (is this right @white238 ?) Either way, I'm fine moving to whippet as TOSS4 is the future.

**Comment by white238** [comment]
Depending on how the ``constexpr`` is evaluated that could be an used parameter. Can you try adding ``[[maybe_unused]]``?

**Comment by chapman39** [comment]
> Depending on how the `constexpr` is evaluated that could be an used parameter. Can you try adding `[[maybe_unused]]`?

that seems to have fixed the issue, thanks!

**Comment by chapman39** [comment]
PR is ready for final review

**Review by white238 — APPROVED** [review]

**Review by ebchin — APPROVED** [review]
