### ISSUE TITLE
Broken with the latest axom release axom-0.10.1

### ISSUE THREAD

**Issue by yurivict** [LLNL/serac#1313]
Rev. 704006a fails to build with axom-0.10.1:
```
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/numerics/odes.cpp:7:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/odes.hpp:19:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/physics/boundary_conditions/boundary_condition_manager.hpp:18:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/physics/boundary_conditions/boundary_condition.hpp:23:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/physics/state/finite_element_state.hpp:23:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/physics/state/finite_element_vector.hpp:22:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/functional.hpp:22:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/integral.hpp:15:
In file included from /usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/geometric_factors.hpp:3:
/usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/element_restriction.hpp:200:42: error: no member named 'Host' in 'axom::MemorySpace'
  200 |   axom::Array<DoF, 2, axom::MemorySpace::Host> dof_info;
      |                       ~~~~~~~~~~~~~~~~~~~^
/usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/element_restriction.hpp:245:40: error: no member named 'Host' in 'axom::MemorySpace'
  245 | axom::Array<DoF, 2, axom::MemorySpace::Host> GetElementDofs(const serac::fes_t* fes, mfem::Geometry::Type geom);
      |                     ~~~~~~~~~~~~~~~~~~~^
/usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/element_restriction.hpp:254:40: error: no member named 'Host' in 'axom::MemorySpace'
  254 | axom::Array<DoF, 2, axom::MemorySpace::Host> GetFaceDofs(const serac::fes_t* fes, mfem::Geometry::Type face_geom,
      |                     ~~~~~~~~~~~~~~~~~~~^
/usr/ports/science/serac/work/serac-704006a/src/serac/infrastructure/../../serac/numerics/functional/element_restriction.hpp:258:40: error: no member named 'Host' in 'axom::MemorySpace'
  258 | axom::Array<DoF, 2, axom::MemorySpace::Host> GetFaceDofs(const serac::fes_t* fes, mfem::Geometry::Type face_geom,
      |                     ~~~~~~~~~~~~~~~~~~~^
```

clang-19
FreeBSD 14.2

**Comment by chapman39** [comment]
Axom and its API fixes will be resolved in this PR https://github.com/LLNL/serac/pull/1312

**Comment by white238** [comment]
This should be fixed in develop. If not please open with more information about how axom and serac are being built by you.
