### PR TITLE
fix input.cpp: bypass possible null deref error

### LINKED ISSUE #443: spec="%gcc@8.3.1 build_type=Release" warning-as-error
Saw this warning-as-error in a LiDO merge request when spec="%gcc@8.3.1 build_type=Release"; partial log below:

```console
==> Installing serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe
==> No binary for serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe found: installing from source
==> serac: Executing phase: 'hostconfig'
==> serac: Executing phase: 'cmake'
==> serac: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
4 errors found in build log:
     157    cd /usr/WS1/oxberry1/.gitlab-runner/builds/XvEgLX5S/3/gitlab/topopt
            /lido-2.0/uberenv_libs/spack/var/spack/stage/spack-stage-serac-deve
            lop-nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack-build-nlbb25r/src/serac/
            coefficients && /usr/tce/packages/cmake/cmake-3.14.5/bin/cmake -E c
            make_link_script CMakeFiles/serac_coefficients.dir/link.txt --verbo
            se=1
     158    /bin/ar qc ../../../lib/libserac_coefficients.a  CMakeFiles/serac_c
            oefficients.dir/loading_functions.cpp.o CMakeFiles/serac_coefficien
            ts.dir/coefficient_extensions.cpp.o
     159    /bin/ranlib ../../../lib/libserac_coefficients.a
     160    make[2]: Leaving directory `/usr/WS1/oxberry1/.gitlab-runner/builds
            /XvEgLX5S/3/gitlab/topopt/lido-2.0/uberenv_libs/spack/var/spack/sta
            ge/spack-stage-serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack
            -build-nlbb25r'
     161    [ 25%] Built target serac_coefficients
     162    /usr/WS1/oxberry1/.gitlab-runner/builds/XvEgLX5S/3/gitlab/topopt/li
            do-2.0/uberenv_libs/spack/var/spack/stage/spack-stage-serac-develop
            -nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack-src/src/serac/infrastructur
            e/input.cpp: In member function 'std::unique_ptr<mfem::Coefficient>
             serac::input::CoefficientInputOptions::constructScalar() const':
  >> 163    /usr/WS1/oxberry1/.gitlab-runner/builds/XvEgLX5S/3/gitlab/topopt/li
            do-2.0/uberenv_libs/spack/var/spack/stage/spack-stage-serac-develop
            -nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack-src/src/serac/infrastructur
            e/input.cpp:154:46: error: potential null pointer dereference [-Wer
            ror=null-dereference]
     164         mfem::Vector pw_constants(max_attr_elem->first);
     165                                   ~~~~~~~~~~~~~~~^~~~~
     166    cc1plus: all warnings being treated as errors
  >> 167    make[2]: *** [src/serac/infrastructure/CMakeFiles/serac_infrastruct
            ure.dir/input.cpp.o] Error 1
     168    make[2]: Leaving directory `/usr/WS1/oxberry1/.gitlab-runner/builds
            /XvEgLX5S/3/gitlab/topopt/lido-2.0/uberenv_libs/spack/var/spack/sta
            ge/spack-stage-serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack
            -build-nlbb25r'
  >> 169    make[1]: *** [src/serac/infrastructure/CMakeFiles/serac_infrastruct
            ure.dir/all] Error 2
     170    make[1]: Leaving directory `/usr/WS1/oxberry1/.gitlab-runner/builds
            /XvEgLX5S/3/gitlab/topopt/lido-2.0/uberenv_libs/spack/var/spack/sta
            ge/spack-stage-serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack
            -build-nlbb25r'
  >> 171    make: *** [all] Error 2
See build log for details:
  /usr/WS1/oxberry1/.gitlab-runner/builds/XvEgLX5S/3/gitlab/topopt/lido-2.0/uberenv_libs/spack/var/spack/stage/spack-stage-serac-develop-nlbb25r7isuacsdfv3p6gtvexjopqdbe/spack-build-out.txt
```

### PR DESCRIPTION
**Pull request by goxberry**
This commit works around a "possible null dereference" error emitted
by Serac builds with "%gcc@8.3.1 build_type=Release" by guarding the
dereference in question with a conditional that only passes control to
the statement dereferencing the potentially null iterator if that
iterator is, in fact, non-null.

Resolves #443.

This warning seems kind of silly because another enclosing conditional ensures the dereferenced iterator is non-null, but the fix is straightforward.

### CODE REVIEW

**Review by white238 — APPROVED** [review]

**Comment by jamiebramwell** [comment]
Closing as this has been merged into https://github.com/LLNL/serac/pull/447.
